language: cpp

sudo: false

addons:
    apt:
        sources:
            - kalakris-cmake
            # - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
            - boost-latest
        packages:
            - binutils-dev
            - libboost-system1.55-dev
            - libboost-thread1.55-dev
            # - clang-3.7
            - cmake
            - libelf-dev
            - g++-4.9

compiler:
    - gcc
    # - clang

script:
    - if [ "$CC" == "clang" ]; then export CC=clang-3.7; export CXX=clang++-3.7; fi
    - if [ "$CC" == "gcc" ]; then export CC=gcc-4.9; export CXX=g++-4.9; fi
    - mkdir work
    - cd work
    - cmake ..
    - make
