build:
    parallel: true
    project: Dyninst.sln
    verbosity: normal

clone_depth: 5

platform:
    - Win32

configuration:
    - Release

environment:
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib32-msvc-14.0

before_build:
    - cmake .
